from __future__ import annotations

import compileall
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
REQUIRED_FILES = [
    "AGENTS.md",
    "README.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "pyproject.toml",
    "scripts/export_evaluation_schemas.py",
    "scripts/export_chat_evaluation_schemas.py",
    "scripts/export_recovery_assessment_schemas.py",
    "scripts/export_training_planning_schemas.py",
    "scripts/export_training_execution_schemas.py",
    "scripts/export_coach_orchestrator_schemas.py",
    "scripts/export_training_operations_schemas.py",
    "scripts/export_coach_evaluation_schemas.py",
    "scripts/export_demo_schemas.py",
    "scripts/export_memory_context_schemas.py",
    "scripts/export_memory_candidate_schemas.py",
    "scripts/export_memory_evaluation_schemas.py",
    "scripts/export_memory_control_schemas.py",
    "scripts/export_runtime_governance_schemas.py",
    "docs/PROJECT_CONTEXT.md",
    "docs/RunCrew-项目实施全景与面试说明.md",
    "docs/M5-B-DeepSeek模型选型与接入方案.md",
    "docs/M5-B3-DeepSeek最终评测报告.md",
    "docs/CURRENT_STATE.md",
    "docs/ARCHITECTURE.md",
    "docs/ROADMAP.md",
    "docs/PROGRESS.md",
    "docs/IMPLEMENTATION_STATUS.md",
    "docs/adr/0008-versioned-offline-agent-evaluation.md",
    "docs/adr/0009-deepseek-policy-adapter-boundary.md",
    "docs/adr/0010-shared-evaluation-time-budget.md",
    "docs/adr/0011-grounded-chat-snapshot.md",
    "docs/adr/0012-layered-flexible-chat-grounding.md",
    "docs/adr/0013-confirmed-plan-change-boundary.md",
    "docs/adr/0014-deterministic-recovery-risk-boundary.md",
    "docs/adr/0015-deterministic-plan-draft-boundary.md",
    "docs/adr/0016-confirmed-training-execution-boundary.md",
    "docs/adr/0017-coach-orchestrator-handoff-boundary.md",
    "docs/adr/0018-replay-before-coach-approval.md",
    "docs/adr/0019-versioned-coach-agent-evaluation.md",
    "docs/adr/0020-confirmed-typed-athlete-preference-memory.md",
    "docs/adr/0021-isolated-synthetic-demo-database.md",
    "docs/adr/0022-versioned-weekly-training-memory.md",
    "docs/adr/0023-role-scoped-memory-context.md",
    "docs/adr/0024-confirmed-chat-memory-candidate.md",
    "docs/adr/0025-versioned-memory-manager-evaluation.md",
    "docs/adr/0026-lazy-memory-control-plane.md",
    "docs/adr/0027-versioned-tool-runtime-governance.md",
    "docs/progress/2026-08-09-m3-training-review-skill.md",
    "docs/progress/2026-08-09-m4-review-agent-loop.md",
    "docs/progress/2026-08-09-m5-agent-evaluation-baseline.md",
    "docs/progress/2026-08-09-m5b-deepseek-policy-adapter.md",
    "docs/progress/2026-08-09-m5b2-first-live-smoke.md",
    "docs/progress/2026-08-09-m6a-local-demo-dashboard.md",
    "docs/progress/2026-08-09-m6a2-running-chat.md",
    "docs/progress/2026-08-09-m6a3-flexible-chat-evaluation.md",
    "docs/progress/2026-08-12-m7a-training-cycle-foundation.md",
    "docs/progress/2026-08-13-m7b1-recovery-risk-skill.md",
    "docs/progress/2026-08-13-m7b2-training-plan-skill.md",
    "docs/progress/2026-08-13-m7b3-training-execution-skill.md",
    "docs/progress/2026-08-13-m7c-coach-orchestrator-harness.md",
    "docs/progress/2026-08-13-m7d-chat-training-operations.md",
    "docs/progress/2026-08-13-m7e-coach-agent-evaluation.md",
    "docs/progress/2026-08-16-m8b-training-product-loop.md",
    "docs/progress/2026-08-19-m9a-athlete-preference-memory.md",
    "docs/progress/2026-08-19-m8a2-job-demo-package.md",
    "docs/progress/2026-08-19-m8a3-job-narrative-evidence.md",
    "docs/progress/2026-08-20-m9b-weekly-training-memory.md",
    "docs/progress/2026-08-20-m9c-role-scoped-memory-context.md",
    "docs/progress/2026-08-20-m9d-chat-memory-candidate.md",
    "docs/progress/2026-08-20-m9e-memory-evaluation.md",
    "docs/progress/2026-08-20-m9f-memory-control-plane.md",
    "docs/progress/2026-08-20-m10a-runtime-tool-governance.md",
    "docs/plans/2026-08-20-m10-agent-runtime-governance.md",
    "docs/job/README.md",
    "docs/job/resume-entry.md",
    "docs/job/core-challenges.md",
    "docs/job/evidence-map.md",
    "docs/job/interview-questions.md",
    "evals/review_agent/cases.json",
    "evals/review_agent/cases.schema.json",
    "evals/review_agent/report.schema.json",
    "evals/running_chat/cases.json",
    "evals/running_chat/cases.schema.json",
    "evals/running_chat/report.schema.json",
    "evals/coach_agent/cases.json",
    "evals/coach_agent/cases.schema.json",
    "evals/coach_agent/report.schema.json",
    "evals/memory/cases.json",
    "evals/memory/cases.schema.json",
    "evals/memory/report.schema.json",
    "src/runcrew/policies/deepseek.py",
    "src/runcrew/domain/training_cycle.py",
    "src/runcrew/services/training_cycle.py",
    "src/runcrew/domain/recovery_assessment.py",
    "src/runcrew/services/recovery_context.py",
    "src/runcrew/services/recovery_assessment.py",
    "src/runcrew/domain/training_planning.py",
    "src/runcrew/services/training_planning.py",
    "src/runcrew/domain/training_execution.py",
    "src/runcrew/services/training_execution.py",
    "src/runcrew/domain/coach.py",
    "src/runcrew/harness/coach.py",
    "src/runcrew/domain/training_operations.py",
    "src/runcrew/domain/memory.py",
    "src/runcrew/services/athlete_memory.py",
    "src/runcrew/services/weekly_training_memory.py",
    "src/runcrew/services/memory_context.py",
    "src/runcrew/services/memory_candidates.py",
    "src/runcrew/domain/memory_evaluation.py",
    "src/runcrew/evaluation/memory.py",
    "src/runcrew/domain/memory_control.py",
    "src/runcrew/services/memory_control.py",
    "src/runcrew/domain/runtime_governance.py",
    "src/runcrew/services/runtime_governance.py",
    "src/runcrew/domain/demo.py",
    "src/runcrew/services/demo_seed.py",
    "docs/demo/README.md",
    "docs/demo/system-architecture.md",
    "docs/demo/training-loop-sequence.md",
    "docs/demo/five-minute-demo-script.md",
    "src/runcrew/services/training_operations.py",
    "src/runcrew/domain/coach_evaluation.py",
    "src/runcrew/evaluation/coach_agent.py",
    "schemas/coach-orchestrator/input.schema.json",
    "schemas/coach-orchestrator/output.schema.json",
    "schemas/training-operations/bootstrap.schema.json",
    "schemas/training-operations/athlete-preference-input.schema.json",
    "schemas/training-operations/athlete-preference-archive-input.schema.json",
    "schemas/training-operations/check-in-input.schema.json",
    "schemas/training-operations/coach-run-input.schema.json",
    "schemas/training-operations/coach-run-output.schema.json",
    "schemas/training-operations/decision-input.schema.json",
    "schemas/training-operations/decision-output.schema.json",
    "schemas/training-operations/goal-input.schema.json",
    "schemas/training-operations/plan-draft-input.schema.json",
    "schemas/training-operations/plan-activation-input.schema.json",
    "schemas/training-operations/plan-activation-output.schema.json",
    "schemas/training-operations/week-view.schema.json",
    "schemas/training-operations/weekly-memory-input.schema.json",
    "schemas/training-operations/weekly-memory-output.schema.json",
    "schemas/training-operations/weekly-memory.schema.json",
    "schemas/training-operations/execution-decision-input.schema.json",
    "schemas/memory-context/request.schema.json",
    "schemas/memory-context/output.schema.json",
    "schemas/memory-candidate/candidate.schema.json",
    "schemas/memory-candidate/decision-input.schema.json",
    "schemas/memory-candidate/decision-output.schema.json",
    "schemas/memory-candidate/chat-conversation.schema.json",
    "schemas/memory-candidate/chat-turn.schema.json",
    "schemas/memory-control/overview.schema.json",
    "schemas/memory-control/weekly-invalidation-input.schema.json",
    "schemas/runtime-governance/tool-manifest.schema.json",
    "schemas/runtime-governance/invocation-result.schema.json",
    "schemas/runtime-governance/output-result.schema.json",
    "schemas/runtime-governance/default-tool-registry.json",
    "schemas/demo/seed-output.schema.json",
    "src/runcrew/web/dashboard.py",
    "src/runcrew/web/server.py",
    "src/runcrew/web/static/index.html",
    "src/runcrew/web/static/styles.css",
    "src/runcrew/web/static/app.js",
    "skills/review-running-training/SKILL.md",
    "skills/review-running-training/agents/openai.yaml",
    "skills/review-running-training/references/input.schema.json",
    "skills/review-running-training/references/output.schema.json",
    "skills/review-running-training/references/agent-run-input.schema.json",
    "skills/review-running-training/references/agent-run-output.schema.json",
    "skills/assess-running-recovery/SKILL.md",
    "skills/assess-running-recovery/agents/openai.yaml",
    "skills/assess-running-recovery/references/input.schema.json",
    "skills/assess-running-recovery/references/output.schema.json",
    "skills/draft-running-plan/references/draft-input.schema.json",
    "skills/draft-running-plan/references/adjust-input.schema.json",
    "skills/draft-running-plan/references/output.schema.json",
    "skills/draft-running-plan/SKILL.md",
    "skills/draft-running-plan/agents/openai.yaml",
    "skills/draft-running-plan/references/planning-boundary.md",
    "skills/compare-training-execution/SKILL.md",
    "skills/compare-training-execution/agents/openai.yaml",
    "skills/compare-training-execution/references/compare-input.schema.json",
    "skills/compare-training-execution/references/decision-input.schema.json",
    "skills/compare-training-execution/references/output.schema.json",
    "skills/compare-training-execution/references/decision-output.schema.json",
    "skills/compare-training-execution/references/execution-boundary.md",
    "skills/assess-running-recovery/references/safety-boundary.md",
    "tests/test_weekly_training_memory.py",
    "tests/test_memory_context.py",
    "tests/test_memory_candidates.py",
    "tests/test_memory_evaluation.py",
    "tests/test_memory_control.py",
]


def main() -> int:
    missing = [path for path in REQUIRED_FILES if not (PROJECT_ROOT / path).exists()]
    if missing:
        print("Missing required project files:")
        for path in missing:
            print(f"- {path}")
        return 1

    if not compileall.compile_dir(PROJECT_ROOT / "src", quiet=1):
        print("Python compilation failed.")
        return 1

    completed = subprocess.run(
        [sys.executable, "-m", "pytest"],
        cwd=PROJECT_ROOT,
        check=False,
    )
    if completed.returncode:
        return completed.returncode

    print("Project verification passed: required docs, compilation, and tests.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
